### ISSUE TITLE
Add/Delete bookmark buttons CSS issue

### ISSUE THREAD

**Issue by camelfert** [soniatallroth/CNMT310FinalProject#7]
There is currently a problem on our bookmarks page with the way that the add/delete buttons are displayed. 

Currently, the delete button is in an ideal spot, but the add button is in the middle of the heading as shown below.

![image](https://user-images.githubusercontent.com/29033079/235260264-712b130c-dff4-4689-8a49-0cf541edba11.png)

The ideal look would be to have the "Bookmarks" text stay where it is, but find a way to push both buttons to the right end of the heading and be right next to each other if at all possible.

I attempted to fix this myself but I had no luck after around an hour of tinkering with many different CSS properties, so I feel it would be best left to someone that knows what they're doing with CSS and design.

**Comment by soniatallroth** [comment]
I haven't fixed that since I thought we were planning on making each bookmark delete when you click the x when hovering over the module. 

If we end up using the actual delete bookmarks button and module in our final product I can fix it, but if not I think it's ok to leave it there for now!
